
## 优惠券 ###
SELECT c.COUPON_ID, c.TITLE, DATE_FORMAT(c.END_DT, '%Y-%m-%d') AS EXPIRED_DATE,  s.SHOP_NAME, s.AVERAGE_PRICE, att.ATTACHMENT_ID, att.EXTENSION_NAME
FROM coupon c
INNER JOIN shop s
ON c.SHOP_ID =  s.SHOP_ID
LEFT JOIN attachment att
ON att.REFERENCE_ID = c.COUPON_ID
WHERE c.VALID_IND = 1
AND c.START_DT <= NOW()
AND c.END_DT >= NOW()
ORDER BY c.UPDATED_DT DESC
LIMIT 5;

## 租房 ###
SELECT hr.RENT_ID, hr.TITLE, hr.RENT_PRICE, hc.NAME AS COM_NAME, att.ATTACHMENT_ID, att.EXTENSION_NAME
FROM house_rent hr
INNER JOIN house_community hc
ON hr.COM_ID = hc.COM_ID
LEFT JOIN attachment att
ON att.REFERENCE_ID = hr.RENT_ID
WHERE att.ATTACHMENT_ID = (SELECT ATTACHMENT_ID FROM attachment WHERE REFERENCE_ID = att.REFERENCE_ID ORDER BY CREATED_DT DESC LIMIT 1)
AND hr.RENT_IND = 0
ORDER BY hr.UPDATED_DT DESC
LIMIT 6;


## 商家 ###
SELECT s.SHOP_ID, s.SHOP_NAME, att.ATTACHMENT_ID, att.EXTENSION_NAME
FROM shop s
LEFT JOIN attachment att
ON att.REFERENCE_ID = s.SHOP_ID
WHERE s.APPROVE_IND = 1
LIMIT 10;

## 跳蚤市场 ###
SELECT sh.SH_ID, sh.TITLE, sh.PRICE, att.ATTACHMENT_ID, att.EXTENSION_NAME
FROM secondhand sh
LEFT JOIN attachment att
ON att.REFERENCE_ID = sh.SH_ID
WHERE att.ATTACHMENT_ID = (SELECT ATTACHMENT_ID FROM attachment WHERE REFERENCE_ID = att.REFERENCE_ID ORDER BY CREATED_DT DESC LIMIT 1)
AND sh.VALID_IND = 1
ORDER BY sh.CREATED_DT DESC
LIMIT 5;
    
